"""
Django settings for ProjetoTCLE project.

Generated by 'django-admin startproject' using Django 6.0.4.

Configuração sensível (chave secreta, senha do banco, hosts, HTTPS) vem de
VARIÁVEIS DE AMBIENTE ou de um arquivo `.env` na raiz do projeto (a pasta que
contém o manage.py). O `.env` NÃO deve ser versionado; use o `.env.example`
como modelo.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/
"""

import os
import sys
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _carregar_env(caminho):
    """Lê um `.env` simples (CHAVE=valor) sem sobrescrever variáveis já definidas."""
    if not caminho.is_file():
        return
    for linha in caminho.read_text(encoding='utf-8-sig').splitlines():
        linha = linha.strip()
        if not linha or linha.startswith('#') or '=' not in linha:
            continue
        chave, valor = linha.split('=', 1)
        valor = valor.strip()
        if len(valor) >= 2 and valor[0] == valor[-1] and valor[0] in '"\'':
            valor = valor[1:-1]
        os.environ.setdefault(chave.strip(), valor)


def _env_bool(nome, padrao):
    valor = os.environ.get(nome)
    if valor is None or valor.strip() == '':
        return padrao
    return valor.strip().lower() in ('1', 'true', 'yes', 'sim', 'on')


def _env_lista(nome, padrao):
    valor = os.environ.get(nome)
    if valor is None or valor.strip() == '':
        return list(padrao)
    return [item.strip() for item in valor.split(',') if item.strip()]


_carregar_env(BASE_DIR / '.env')

TESTING = len(sys.argv) > 1 and sys.argv[1] == 'test'


# SECURITY: nada de segredo no código. O padrão é produção (DEBUG desligado).
# Para desenvolvimento local defina DJANGO_DEBUG=True no seu `.env`.
DEBUG = _env_bool('DJANGO_DEBUG', False)

SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', '')
if not SECRET_KEY:
    if DEBUG or TESTING:
        # Somente desenvolvimento/testes: chave gerada e guardada localmente
        # (arquivo ignorado pelo git) para as sessões sobreviverem a reinícios.
        _arquivo_chave = BASE_DIR / '.dev_secret_key'
        try:
            SECRET_KEY = _arquivo_chave.read_text(encoding='utf-8').strip()
        except OSError:
            SECRET_KEY = ''
        if not SECRET_KEY:
            from django.core.management.utils import get_random_secret_key
            SECRET_KEY = get_random_secret_key()
            try:
                _arquivo_chave.write_text(SECRET_KEY, encoding='utf-8')
            except OSError:
                pass
    else:
        raise ImproperlyConfigured(
            'Defina a variável de ambiente DJANGO_SECRET_KEY (veja o arquivo .env.example).'
        )

ALLOWED_HOSTS = _env_lista('DJANGO_ALLOWED_HOSTS', ['localhost', '127.0.0.1', '[::1]'])
CSRF_TRUSTED_ORIGINS = _env_lista('DJANGO_CSRF_TRUSTED_ORIGINS', [])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'appTCLE',
    'usuarios',
    'pacientes',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Bloqueia usuários de unidade inativa e impede cache de páginas com dados de pacientes
    'usuarios.middleware.AcessoSeguroMiddleware',
    # Bloqueia todo o sistema enquanto a senha inicial não for trocada
    'usuarios.middleware.TrocaSenhaObrigatoriaMiddleware',
]

ROOT_URLCONF = 'ProjetoTCLE.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'usuarios.context_processors.unidade_ativa_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'ProjetoTCLE.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if os.environ.get('DB_ENGINE', 'postgresql').strip().lower() == 'sqlite':
    # Apenas para testes/desenvolvimento rápido (DB_ENGINE=sqlite).
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.environ.get('DB_NAME', str(BASE_DIR / 'db.sqlite3')),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'TCLE'),
            'USER': os.environ.get('DB_USER', 'postgres'),
            'PASSWORD': os.environ.get('DB_PASSWORD', ''),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '5432'),
        }
    }
    if os.environ.get('DB_SSLMODE'):
        DATABASES['default']['OPTIONS'] = {'sslmode': os.environ['DB_SSLMODE']}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        # Política do sistema: 8+ caracteres, letra, número, caractere especial e sem sequências numéricas
        'NAME': 'usuarios.validators.PoliticaSenhaValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Bahia'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

AUTH_USER_MODEL = 'usuarios.Usuario'
LOGIN_URL = 'login'

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'
# Habilita o login usando E-mail
AUTHENTICATION_BACKENDS = [
    'usuarios.backends.EmailBackend', # Nosso motor customizado (E-mail)
    'django.contrib.auth.backends.ModelBackend', # Motor padrão (Username) fallback
]

# ---------------------------------------------------------------------------
# Sessões, cookies e HTTPS
# ---------------------------------------------------------------------------
# Sessão expira por inatividade (padrão: 60 min, renovada a cada requisição) e
# ao fechar o navegador. Os cookies não são acessíveis por JavaScript.
SESSION_COOKIE_AGE = int(os.environ.get('DJANGO_SESSAO_MINUTOS', '60')) * 60
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

# Fora do modo DEBUG assume-se HTTPS (cookies "secure", redirecionamento e HSTS).
# Em rede interna sem HTTPS, defina DJANGO_HTTPS=False de forma consciente.
HTTPS = _env_bool('DJANGO_HTTPS', not DEBUG and not TESTING)
SESSION_COOKIE_SECURE = HTTPS
CSRF_COOKIE_SECURE = HTTPS
SECURE_SSL_REDIRECT = HTTPS
SECURE_HSTS_SECONDS = int(os.environ.get('DJANGO_HSTS_SEGUNDOS', '31536000' if HTTPS else '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = HTTPS
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'same-origin'
X_FRAME_OPTIONS = 'DENY'
if _env_bool('DJANGO_ATRAS_DE_PROXY', False):
    # Somente se houver um proxy reverso confiável que sobrescreva este cabeçalho.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Caminho do painel /admin/ (pode ser alterado por variável de ambiente).
ADMIN_URL = os.environ.get('DJANGO_ADMIN_URL', 'admin/').strip('/') + '/'

# ---------------------------------------------------------------------------
# Envio de E-mail (usado para enviar o TCLE em PDF ao paciente no Histórico)
# Configure as variáveis de ambiente abaixo em produção. Enquanto DEBUG=True
# e nenhum EMAIL_HOST for definido, os e-mails são apenas impressos no
# console (não são enviados de verdade), para não travar o desenvolvimento.
# ---------------------------------------------------------------------------
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
if EMAIL_HOST:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
    EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

EMAIL_TIMEOUT = 15
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'nao-responda@tcledigital.com.br')
