# Generated by Django 6.0.4 on 2026-06-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='primeiro_acesso',
            field=models.BooleanField(default=True, verbose_name='Primeiro Acesso'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='profissao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Profissão'),
        ),
    ]
