# Generated by Django 6.0.7 on 2026-07-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_primeiro_acesso_usuario_profissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='registro_profissional',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Registro Profissional (CRM/COREN/etc)'),
        ),
    ]
