# Generated by Django 6.0.4 on 2026-07-17 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_usuario_primeiro_acesso_usuario_profissao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição / Notas de Orientação')),
                ('texto_padrao', models.TextField(blank=True, default='', help_text='Texto fixo obrigatório da categoria. Pode conter variáveis (@profissional, @paciente, @rgpaciente, @responsavel, @rgresponsavel, @data) e campos personalizados no formato [Nome do Campo].', verbose_name='Texto Padrão da Categoria')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='usuarios.instituicao')),
            ],
            options={
                'unique_together': {('instituicao', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('rg', models.CharField(max_length=20, verbose_name='RG')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('tipo_logradouro', models.CharField(max_length=20, verbose_name='Tipo de Logradouro')),
                ('logradouro', models.CharField(max_length=255, verbose_name='Logradouro')),
                ('numero', models.CharField(max_length=20, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='usuarios.instituicao')),
            ],
            options={
                'unique_together': {('instituicao', 'cpf')},
            },
        ),
        migrations.CreateModel(
            name='TemplateTCLE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título do Template')),
                ('texto_base', models.TextField(verbose_name='Texto Base do Termo')),
                ('configuracao_campos', models.JSONField(blank=True, default=dict, verbose_name='Configuração dos Campos Dinâmicos')),
                ('ativo', models.BooleanField(default=True, verbose_name='Disponível para os Médicos')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='pacientes.categoriatemplate')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='usuarios.instituicao')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoEmitido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dados_preenchidos', models.JSONField(verbose_name='Dados Colectados')),
                ('responsavel_nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Responsável')),
                ('responsavel_cpf', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF do Responsável')),
                ('status', models.CharField(choices=[('PENDENTE', 'Aguardando Assinatura'), ('ASSINADO', 'Concluído e Selado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20)),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='termos_selados/%Y/%m/%d/')),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.instituicao')),
                ('medico_emissor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pacientes.paciente')),
                ('template_origem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pacientes.templatetcle')),
            ],
        ),
    ]
