# Generated by Django 6.0.4 on 2026-06-18 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriatemplate',
            name='instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='usuarios.instituicao'),
        ),
        migrations.AddField(
            model_name='documentoemitido',
            name='instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.instituicao'),
        ),
        migrations.AddField(
            model_name='documentoemitido',
            name='medico_emissor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paciente',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paciente',
            name='instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='usuarios.instituicao'),
        ),
        migrations.AddField(
            model_name='documentoemitido',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pacientes.paciente'),
        ),
        migrations.AddField(
            model_name='templatetcle',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='pacientes.categoriatemplate'),
        ),
        migrations.AddField(
            model_name='templatetcle',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='templatetcle',
            name='instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='usuarios.instituicao'),
        ),
        migrations.AddField(
            model_name='documentoemitido',
            name='template_origem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pacientes.templatetcle'),
        ),
        migrations.AlterUniqueTogether(
            name='categoriatemplate',
            unique_together={('instituicao', 'nome')},
        ),
        migrations.AlterUniqueTogether(
            name='paciente',
            unique_together={('instituicao', 'cpf')},
        ),
    ]
