# Generated by Django 6.0.4 on 2026-05-26 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RG'),
        ),
        migrations.CreateModel(
            name='TemplateTCLE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Template')),
                ('categoria', models.CharField(choices=[('CIRURGICO', 'Procedimentos Cirúrgicos'), ('ANESTESICO', 'Procedimentos Anestésicos'), ('EXAME', 'Exames Diagnósticos Invasivos'), ('HEMOTERAPIA', 'Hemoterapia'), ('ODONTO', 'Procedimentos Odontológicos'), ('ALTO_RISCO', 'Terapias de Alto Risco')], max_length=20, verbose_name='Categoria')),
                ('texto_base', models.TextField(verbose_name='Texto do Documento')),
                ('ativo', models.BooleanField(default=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
