# Generated by Django 6.0.7 on 2026-07-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoemitido',
            name='assinatura_paciente',
            field=models.TextField(blank=True, null=True, verbose_name='Assinatura do Paciente/Responsável (base64)'),
        ),
        migrations.AddField(
            model_name='documentoemitido',
            name='assinatura_profissional',
            field=models.TextField(blank=True, null=True, verbose_name='Assinatura do Profissional (base64)'),
        ),
        migrations.AddField(
            model_name='documentoemitido',
            name='responsavel_rg',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RG do Responsável'),
        ),
        migrations.AddField(
            model_name='documentoemitido',
            name='texto_final',
            field=models.TextField(blank=True, default='', verbose_name='Texto Final do Termo (com variáveis substituídas)'),
        ),
    ]
