# Generated by Django 6.0.4 on 2026-07-15 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriatemplate',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categoriatemplate',
            name='texto_padrao',
            field=models.TextField(blank=True, default='', help_text='Texto fixo obrigatório da categoria. Pode conter variáveis (@profissional, @paciente, @responsavel, @data) e campos personalizados no formato {Nome do Campo}.', verbose_name='Texto Padrão da Categoria'),
        ),
    ]
