# Generated by Django 6.0.7 on 2026-08-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_documentoemitido_assinatura_paciente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoemitido',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Aguardando Assinatura'), ('ASSINADO', 'Concluído e Selado'), ('RECUSADO', 'Recusado pelo Paciente'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20),
        ),
    ]
